---
Name: silverstripe-forager-elastic-enterprise
Only:
  envvarset: 'ENTERPRISE_SEARCH_API_KEY'
After:
  - 'silverstripe-search-service-dataobject'
  - 'search-service-default'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forager\Service\IndexConfiguration:
    constructor:
      index_variant: '`ENTERPRISE_SEARCH_ENGINE_PREFIX`'
  SilverStripe\Forager\Interfaces\IndexingInterface:
    class: SilverStripe\ForagerElasticEnterprise\Service\EnterpriseSearchService
    constructor:
      client: '%$Elastic\EnterpriseSearch\Client'
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'
      builder: '%$SilverStripe\Forager\Service\DocumentBuilder'
  Elastic\EnterpriseSearch\Client:
    factory: SilverStripe\ForagerElasticEnterprise\Service\ClientFactory
    constructor:
      host: '`ENTERPRISE_SEARCH_ENDPOINT`'
      token: '`ENTERPRISE_SEARCH_API_KEY`'
      http_client: '%$GuzzleHttp\Client'

## customise the dataobject fields for EnterpriseSearch compatability
SilverStripe\Forager\DataObject\DataObjectDocument:
  id_field: record_id
  base_class_field: record_base_class
  page_content_field: page_content
